//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Control</string>\r\n  <string>Shift</string>\r\n  <string>C</string>\r\n</ArrayO" +
            "fString>")]
        public global::System.Collections.Specialized.StringCollection RemoteCopy {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RemoteCopy"]));
            }
            set {
                this["RemoteCopy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Control</string>\r\n  <string>Shift</string>\r\n  <string>R</string>\r\n</ArrayO" +
            "fString>")]
        public global::System.Collections.Specialized.StringCollection SwitchServer {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SwitchServer"]));
            }
            set {
                this["SwitchServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Control</string>\r\n  <string>Shift</string>\r\n  <string>V</string>\r\n</ArrayO" +
            "fString>")]
        public global::System.Collections.Specialized.StringCollection RemotePaste {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RemotePaste"]));
            }
            set {
                this["RemotePaste"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Control</string>\r\n  <string>Shift</string>\r\n  <string>V</string>\r\n</ArrayO" +
            "fString>")]
        public global::System.Collections.Specialized.StringCollection CloseWindow {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CloseWindow"]));
            }
            set {
                this["CloseWindow"] = value;
            }
        }
    }
}
